<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Nitin" failures="4" tests="7" name="AccountsPageTest" time="58.212" errors="0" timestamp="2023-08-21T17:26:53 IST">
  <testcase classname="com.qa.opencart.TestClass.AccountsPageTest" name="accPageHeadersCountTest" time="1.225"/>
  <testcase classname="com.qa.opencart.TestClass.AccountsPageTest" name="accountsPageTitleTest" time="0.208"/>
  <testcase classname="com.qa.opencart.TestClass.AccountsPageTest" name="logoutLinkExistsTest" time="0.193"/>
  <testcase classname="com.qa.opencart.TestClass.AccountsPageTest" name="searchTest" time="5.626">
    <failure type="java.lang.AssertionError" message="expected [3] but found [0]">
      <![CDATA[java.lang.AssertionError: expected [3] but found [0]
at com.qa.opencart.TestClass.AccountsPageTest.searchTest(AccountsPageTest.java:58)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- searchTest -->
  <testcase classname="com.qa.opencart.TestClass.AccountsPageTest" name="searchTest" time="2.636">
    <failure type="java.lang.AssertionError" message="expected [3] but found [0]">
      <![CDATA[java.lang.AssertionError: expected [3] but found [0]
at com.qa.opencart.TestClass.AccountsPageTest.searchTest(AccountsPageTest.java:58)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- searchTest -->
  <testcase classname="com.qa.opencart.TestClass.AccountsPageTest" name="searchTest" time="1.76">
    <failure type="java.lang.AssertionError" message="expected [1] but found [0]">
      <![CDATA[java.lang.AssertionError: expected [1] but found [0]
at com.qa.opencart.TestClass.AccountsPageTest.searchTest(AccountsPageTest.java:58)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- searchTest -->
  <testcase classname="com.qa.opencart.TestClass.AccountsPageTest" name="searchTest" time="1.853">
    <failure type="java.lang.AssertionError" message="expected [7] but found [0]">
      <![CDATA[java.lang.AssertionError: expected [7] but found [0]
at com.qa.opencart.TestClass.AccountsPageTest.searchTest(AccountsPageTest.java:58)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- searchTest -->
</testsuite> <!-- AccountsPageTest -->
